version: "1.0"
info:
  model: int-scaffold
packages:
- name: SerengetiGH2809Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
- name: MultiplyPublicService
  version: "6.0"
  gitServerName: srcCtrl_shared_bitbucket_Arti
  gitUrl: https://bitbucket.org/testartiibm
  gitUsername: artik
  gitBranch: master
services:
- serviceName: project.serengetigh2809.integrations:bitbucketfs
  packages:
  - name: SerengetiGH2809Project
    version: "1.0"
  - name: MultiplyPublicService
    version: "6.0"
- serviceName: MultiplyPublicService:multiply_svc
  packages:
  - name: MultiplyPublicService
    version: "6.0"
- serviceName: pub.math:multiplyInts
  packages:
  - name: WmPublic
    version: 12.1.0.0.1032
